name: latex-build
on: [push]
jobs:
  integ-proba-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: integ-proba/integ-proba.tex