name: latex-build
on: [push]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: integ-proba.tex
          working_directory: integ-proba
      #- name: Artifacts prod
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: integ-proba.pdf
      #    path: integ-proba/integ-proba.pdf
      - name: Publication
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: out
          FOLDER: integ-proba
          CLEAN: true
