name: latex-build
on: [push]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: integ-proba/integ-proba.tex
      - name: Artifacts prod
        uses: actions/upload-artifact@v2
        with:
          name: integ-proba
          path: output/integ-proba.pdf